name: Audit
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: linuxbrew/brew
    steps:
    - name: Changed Files Exporter
      uses: futuratrepadeira/changed-files@v3.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Brew build
      run: "brew install ${{ steps.files.outputs.files_updated }} ${{ steps.files.outputs.files_created }}"